#pragma once
#define FIRMWARE_VERSION_MAJOR 1
#define FIRMWARE_VERSION_MINOR 0
#define FIRMWARE_VERSION_PATCH 0
#define FIRMWARE_VERSION_STR "1.0.0"
#define PROJECT_NAME "RADAR"
#define BUILD_DATE __DATE__
#define BUILD_TIME __TIME__
